CanalTP\MttBundle\Entity\Network:
    type: entity
    table: mtt.network
    repositoryClass: CanalTP\MttBundle\Entity\NetworkRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        externalId:
            type: string
            length: 255
            column: external_id
        externalCoverageId:
            type: string
            length: 255
            column: external_coverage_id
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        seasons:
            targetEntity: Season
            mappedBy: network
            orderBy:
                startDate: ASC
        ditributionLists:
            targetEntity: DistributionList
            mappedBy: network
    manyToMany:
        users:
            targetEntity: CanalTP\SamEcoreUserManagerBundle\Entity\User
            joinTable:
                name: mtt.users_networks
                joinColumns:
                    network_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
        layouts:
            targetEntity: CanalTP\MttBundle\Entity\Layout
            joinTable:
                name: mtt.layouts_networks
                joinColumns:
                    network_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    layout_id:
                        referencedColumnName: id
