parameters:
    mtt.permissions:
        BUSINESS_EDIT_PERIMETERS:
            label: Éditer les réseaux
            description: Permet d'éditer les réseaux (coverageId, networkId, token)
        BUSINESS_ASSIGN_NETWORK_LAYOUT:
            label: Assigner un modèle à un réseau
            description: Permet dans l'application d'indiquer quels templates sont utilisables pour chaque réseau
        BUSINESS_VIEW_NAVITIA_LOG:
            label: AJOUTER VISU INFO DEBUG
            description: Accéder aux informations de debug et aux appels Navitia
        BUSINESS_CHOOSE_LAYOUT:
            label: Choisir les modèles
            description: Permet de choisir un modèle pour chaque ligne puis de le modifier ultérieurement
        BUSINESS_EDIT_LAYOUT:
            label: Éditer les fiches horaires
            description: Permet d'éditer les fiches horaires au niveau arrêt et au niveau route.
        BUSINESS_MANAGE_SEASON:
            label: Gérer les saisons
            description: Permet de créer de modifier (changer le nom le statut ou les dates) et supprimer une saison
        BUSINESS_GENERATE_PDF:
            label: Générer les PDF
            description: Permet de générer les PDF d'une fiche horaire à l'arrêt
        BUSINESS_LIST_AREA:
            label: Lister les secteurs
            description: Permet de lister les secteurs
        BUSINESS_MANAGE_AREA:
            label: Gestion des secteurs
            description: Permet d'éditer, créer, supprimer un secteur.
        BUSINESS_LIST_LAYOUT_CONFIG:
            label: Lister les layouts
            description: Permet de lister les layouts
        BUSINESS_MANAGE_LAYOUT_CONFIG:
            label: Gestion des layouts
            description: Permet d'éditer, créer, supprimer un layout.
        BUSINESS_MANAGE_CUSTOMER:
            label: Administrer les clients
            description: Donner des droits aux clients.
