parameters:
    mtt.permissions:
        BUSINESS_EDIT_PERIMETERS:
            label: Éditer les réseaux
            description: Permet d'éditer les réseaux (coverageId, networkId, token)
        BUSINESS_ASSIGN_NETWORK_LAYOUT:
            label: Assigner un modèle à un client
            description: Permet dans l'application d'indiquer quels modèles sont utilisables pour chaque client
        BUSINESS_VIEW_NAVITIA_LOG:
            label: AJOUTER VISU INFO DEBUG
            description: Accéder aux informations de debug et aux appels Navitia
        BUSINESS_CHOOSE_LAYOUT:
            label: Choisir les fonds de fiche
            description: Permet de choisir un fond de fiche pour chaque ligne puis de le modifier ultérieurement
        BUSINESS_EDIT_LAYOUT:
            label: Éditer les fiches horaires
            description: Permet d'éditer les fiches horaires au niveau arrêt et au niveau route.
        BUSINESS_MANAGE_SEASON:
            label: Gérer les saisons
            description: Permet de créer, de modifier (changer le nom, le statut ou les dates) et supprimer une saison
        BUSINESS_MANAGE_DISTRIBUTION_LIST:
            label: Gérer la liste de distribution
            description: Permet de modifier et de sauvergarder les modifications dans les listes de gestion de la distribution
        BUSINESS_GENERATE_DISTRIBUTION_LIST_PDF:
            label: Générer une liste de distribution
            description: Permet de générer le PDF d'une liste de distribution. /!\ Warning /!\ Si un utilisateur possède cette permission sans posséder celle permettant de générer les pdf des fiches horaires, les listes de distributions générées pourront être incomplètes.
        BUSINESS_GENERATE_PDF:
            label: Générer les PDF
            description: Permet de générer les PDF d'une fiche horaire à l'arrêt, d'un secteur ou d'une saison
        BUSINESS_LIST_AREA:
            label: Lister les secteurs
            description: Permet de lister les secteurs
        BUSINESS_MANAGE_AREA:
            label: Gérer des secteurs
            description: Permet d'éditer, créer, supprimer un secteur.
        BUSINESS_LIST_LAYOUT_CONFIG:
            label: Lister les fonds de fiche
            description: Permet de lister les fonds de fiche
        BUSINESS_MANAGE_LAYOUT_CONFIG:
            label: Gestion des fonds de fiche
            description: Permet d'éditer, créer, supprimer un fond de fiche.
        BUSINESS_MANAGE_CUSTOMER:
            label: Administrer les clients
            description: Donner des droits aux clients.
