CanalTP\MttBundle\Entity\Network:
    properties:
        externalCoverageId:
            - NotBlank: ~
        externalId:
            - CanalTP\MttBundle\Validator\Constraints\ContainsNavitiaNetworkId: ~

CanalTP\MttBundle\Entity\Block:
    properties:
        title:
            - NotBlank: ~
            - Length:
                max: 255

CanalTP\MttBundle\Entity\Season:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [title, network]
        - CanalTP\MttBundle\Validator\Constraints\NotOverlappingEntity: 
            parent: network
            siblings: seasons
            startField: startDate
            endField: endDate
            message: error.seasons_overlapping
    properties:
        title:
            - NotBlank: ~
            - Length:
                max: 255
        startDate:
            - DateTime: ~
        endDate:
            - DateTime: ~
            - CanalTP\MttBundle\Validator\Constraints\GreaterThanField:
                field: startDate
